### ISSUE TITLE
The counts for all statistics in Stage and GitHub do not always match.

### ISSUE THREAD

**Issue by farahfarahmand** [Project-Heimdall/home#59]
[unmatched Stats Counts.pptx](https://github.com/Project-Heimdall/home/files/394733/unmatched.Stats.Counts.pptx)
Steps to reproduce:
1. Select a card on Popular or Explore views
2. Open the same card on GitHub.com and compare the counts for the statistics (Stars, Watchers, Contributors, Commits, Releases, Forks)

Expected Result: The counts should match
Actual Result: The counts do not match

**Comment by camelspeed** [comment]
I have not verified the code or checked every stat but what it is probably happening is a data sync issue.  The data on public Github is real-time (ie it changes every minute of every day) but the data in our system was taken at a moment in time so we are expected to be out of sync.  In a real production scenario we'd have events propagate to us so we are in sync.  I will close this for now since it appears to be working per the current context.
